db:
    host: localhost
    db: test
    user: root
    password: ''''''
    port: 3306
    charset: utf8
    collation: utf8_unicode_ci
    driver: mysql
app:
    namespace: MyApp
    controllers_namespace: \Controllers
    models_namespace: \Models
    controllers_path: /app/controllers/
    models_path: /app/models
